# Generated by Django 3.2.18 on 2023-03-31 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
