# Generated by Django 3.2.18 on 2023-03-31 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebank', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country_of_citizenship',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='passport_scan',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='utility_bill_scan',
        ),
        migrations.AddField(
            model_name='customer',
            name='citizenship',
            field=models.CharField(default=112, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='country_of_residence',
            field=models.CharField(default=4322, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='passport',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='passports/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='utility_bill',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='utility_bills/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(default=2121, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ssn',
            field=models.CharField(max_length=11),
        ),
    ]
