# Generated by Django 3.2.18 on 2023-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebank', '0004_auto_20230331_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ssn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
