# Generated by Django 3.2.18 on 2023-04-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebank', '0006_bankaccount_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remark',
            field=models.CharField(default=1000, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
